### ISSUE TITLE
num_layers and hidden_size

### ISSUE THREAD

**Issue by kensekense** [akb89/ortografix#2]
When running with additional layers, the hidden_size needs to be adjusted, but I'm not sure how to adjust those values with the parameters offered.

Error given is:

```
RuntimeError: Expected hidden size (3, 1, 256), got (1, 1, 256)
```

**Comment by kensekense** [comment]
I also get the same issue when I use bidirectionality, causing the hidden size to expect `(2, 1, 256), got (1, 1, 256)`

**Comment by akb89** [comment]
Ok I fixed the first one, I still need to fix the bidir bug. Sorry about that. I'll let you know asap when it's fixed. I'll push everything under v0.3.3

**Comment by kensekense** [comment]
Sounds good!

**Comment by akb89** [comment]
Ok should be fixed now, let me know if not
