### ISSUE TITLE
Dropout issue with number of layers?

### ISSUE THREAD

**Issue by kensekense** [akb89/ortografix#3]
I'm not 100% sure this is an issue, but it relates to the issue with the number of layers, and how I am not certain how to properly align the hidden_size given the additional layers.
```
UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
```

**Comment by akb89** [comment]
Related to the other issue, closing
